### ISSUE TITLE
[code optimize suggestion] getting JOBS  by using command nproc: $(( $(nproc) * 2 ))

### ISSUE THREAD

**Issue by tcler** [sunhaiyong1978/Yongbao#15]
Command **nproc** has been provided from 2009 by [coreutils](https://github.com/coreutils/coreutils) package;  
Almost all linux distributions that released after 2010 have included it.  

So we can optimize the **JOBS** getting code with nproc: `$(( $(nproc) * 2 ))`

**Comment by sunhaiyong1978** [comment]
感谢，并且巧合的是我本地验证中的版本也已经改用nproc来作为JOBS的计算了。

**Comment by tcler** [comment]
Good to know that :)  
BTW: 我在网上了解到 Fedora-remix-loongarch64 项目也是您的领导下构建的，表达一下感谢和仰慕 : )

**Comment by sunhaiyong1978** [comment]
你客气了。:-)

**Comment by tcler** [comment]
> 你客气了。:-)

;-) 给你 sunhaiyong@zdbr.net 发了一个邮件，有意给 fedora-remix-loongarch 项目做点贡献，还需要人吗?
