### ISSUE TITLE
target_base/glibc制作错误!

### ISSUE THREAD

**Issue by liangyongxiang** [sunhaiyong1978/Yongbao#6]
target_base/glibc制作错误!
错误日志请查看 /home/yongxiang/work/loong/Yongbao/loongarch64/workbase/logs/glibc_target_base_00003.log 文件。

glibc_target_base_00003.log 如下：
https://gist.github.com/liangyongxiang/9ca24b7d842428540d3000b968e6e083

**Comment by sunhaiyong1978** [comment]
信息不完整吗？我未看到日志中的错误内容。

**Comment by liangyongxiang** [comment]
workbase/logs/current.log 的内容：
https://gist.github.com/liangyongxiang/aa0e154f30cedb6b11efbfd5ed76fbc0

**Comment by liangyongxiang** [comment]
我检查了一下，的确是不完整的。大概是gist的限制。

https://fars.ee/MouR

**Comment by liangyongxiang** [comment]
> 我检查了一下，的确是不完整的。大概是gist的限制。
> 
> https://fars.ee/MouR

是完整的。是gist web的限制，可以在这里查看：https://gist.githubusercontent.com/liangyongxiang/9ca24b7d842428540d3000b968e6e083/raw/f6c4e2a2c40d882f619acbbc7833eb9d956b3830/homeyongxiangworkloongYongbaoloongarch64workbaselogsglibc_target_base_00003.log

**Comment by sunhaiyong1978** [comment]
看了一下，目前猜测可能是系统环境中除了Yongbao构建的交叉工具链之外，在PATH路径中可能有其他loongarch64-unknown-linux-gnu-g++可以运行，我修改了相关的构建脚本，你更新一下再编译试试。

**Comment by liangyongxiang** [comment]
> 看了一下，目前猜测可能是系统环境中除了Yongbao构建的交叉工具链之外，在PATH路径中可能有其他loongarch64-unknown-linux-gnu-g++可以运行，我修改了相关的构建脚本，你更新一下再编译试试。

是的。我主系统是  gentoo， 通过crossdev 安装 loongarch64-unknown-linux-gnu-gcc。glibc的问题解决了。

**Comment by sunhaiyong1978** [comment]
感谢找到了一个兼容性的问题，希望可以发现更多类似问题。
