### ISSUE TITLE
host-tools/sqlite制作错误!

### ISSUE THREAD

**Issue by liangyongxiang** [sunhaiyong1978/Yongbao#7]
sqlite_host-tools_00014.log：https://gist.github.com/liangyongxiang/26a2ff68f58e06aa36f84b24afbba675

**Comment by sunhaiyong1978** [comment]
我看看。

**Comment by sunhaiyong1978** [comment]
这个问题是因为系统中带了tcl的开发库导致编译sqlite的时候自动增加了tcl部分支持的编译，安装的时候试图安装到系统的目录中而导致的错误。
目前我已更新host-tools/sqlite中的编译参数避免进行tcl支持的编译，可解决该问题。
目前已经可以同步代码。
感谢你找到该问题。

**Comment by liangyongxiang** [comment]
问题已经解决了。
