### ISSUE TITLE
target_base/gcc制作错误!

### ISSUE THREAD

**Issue by liangyongxiang** [sunhaiyong1978/Yongbao#9]
log : https://gist.github.com/liangyongxiang/689ff989a84ad971d57ef11d8563fcf0

raw log: https://gist.githubusercontent.com/liangyongxiang/689ff989a84ad971d57ef11d8563fcf0/raw/227337344255eb82cf6183333a836b5f995e3ed0/homeyongxiangworkloongYongbaoloongarch64workbaselogsgcc_target_base_00014.log

**Comment by sunhaiyong1978** [comment]
看了一下，初步分析还是因为系统中带了loongarch64-unknow-linux-gnu工具链导致的问题，更新了cross-tools/gcc来解决这个问题。

**Comment by sunhaiyong1978** [comment]
同步一下再./build.sh看看

**Comment by liangyongxiang** [comment]
同步之后重新执行./build.sh 遇到新的错误：
https://gist.githubusercontent.com/liangyongxiang/476d3eceaa89c097328e27afc2beedaa/raw/b3d7900623c4ff8033daf5388f9c0aa77e5d85d5/homeyongxiangworkloongYongbaoloongarch64workbaselogsgcc_cross-tools_00005.log

```
msgfmt: symbol lookup error: /home/yongxiang/work/loong/Yongbao/loongarch64/workbase/cross-tools/lib/libxml2.so.2: undefined symbol: UCNV_FROM_U_CALLBACK_STOP
msgfmt: symbol lookup error: /home/yongxiang/work/loong/Yongbao/loongarch64/workbase/cross-tools/lib/libxml2.so.2: undefined symbol: UCNV_FROM_U_CALLBACK_STOP
```

**Comment by sunhaiyong1978** [comment]
我需要确认一下问题，你试一下以下的步骤：
./build.sh -f host-tools/libxml2
然后再重新执行：
./build.sh

**Comment by liangyongxiang** [comment]
先构建libxml2然后重新执行是可以工作的。

**Comment by sunhaiyong1978** [comment]
那我大概知道问题原因了，应该是host-tools里面编译顺序的问题，我稍后会提交调整后的版本，你可以先继续编译。

**Comment by liangyongxiang** [comment]
继续编译遇到的问题是: https://github.com/sunhaiyong1978/Yongbao/issues/10

**Comment by liangyongxiang** [comment]
之前尝试过清理掉除了source之前的所有修改重新构建，这个问题应该也是解决了
